# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: SublimeHQ.SublimeText.4
PackageVersion: 4.0.0.418000
PackageLocale: en-US
Publisher: Sublime HQ Pty Ltd
PublisherUrl: https://www.sublimetext.com/
PublisherSupportUrl: https://www.sublimetext.com/support
PrivacyUrl: https://forum.sublimetext.com/privacy
Author: Sublime HQ Pty Ltd
PackageName: Sublime Text 4
PackageUrl: https://www.sublimetext.com/
License: Proprietary
LicenseUrl: https://www.sublimetext.com/eula
Copyright: Copyright (c) Sublime HQ Pty Ltd.
CopyrightUrl: https://www.sublimetext.com/eula
ShortDescription: Sublime is a sophisticated cross-platform text editor for code, markup and prose.
Moniker: sublimetext4
Tags:
- editor
- text
- text-editor
ReleaseNotes: "''"
ReleaseNotesUrl: https://www.sublimetext.com/download
Documentations:
- DocumentLabel: Official Documentation
  DocumentUrl: https://www.sublimetext.com/docs/
- DocumentLabel: Community-driven Documentation
  DocumentUrl: https://docs.sublimetext.io/
Icons:
- IconUrl: https://www.sublimehq.com/images/sublime_text.png
  IconFileType: png
  IconResolution: custom
ManifestType: defaultLocale
ManifestVersion: 1.9.0
